baseURL = "https://atom-robotics-lab.github.io/"
title = "ATOM Labs"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "ATOM Labs"

description = "A robotics Community based out of Delhi"
keywords = "blog,developer,personal"
info = ["Robotics community based in Delhi"]
avatarURL = "images/logo.png"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2021

colorScheme = "dark"

hideColorSchemeToggle = false

maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/atom-robotics-labs"



[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://atom-robotics-lab.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Wiki"
weight = 2
url = "/wiki"

[[languages.en.menu.main]]
name = "Sessions"
weight = 3
url = "sessions/"

[[languages.en.menu.main]]
name = "Events"
weight = 4
url = "events/"

[[languages.en.menu.main]]
name = "Contact us"
weight = 5
url = "contact/"

